ALTER TABLE t_p71821556_real_estate_catalog_.purposes ADD COLUMN IF NOT EXISTS icon VARCHAR(50) NULL;

INSERT INTO t_p71821556_real_estate_catalog_.purposes (name, slug, icon, sort_order, is_active) VALUES
('Столовая', 'stolovaya', 'UtensilsCrossed', 20, true),
('Кафе', 'kafe', 'Coffee', 21, true),
('Ресторан', 'restoran', 'Utensils', 22, true),
('Кофейня', 'kofeynya', 'Coffee', 23, true),
('Бургерная', 'burgernaya', 'Utensils', 24, true),
('Бар', 'bar', 'Wine', 25, true),
('Паб', 'pab', 'Beer', 26, true),
('Пиццерия', 'pitseriya', 'Pizza', 27, true),
('Суши-бар/роллы', 'sushi_bar', 'Utensils', 28, true),
('Пекарня-кондитерская', 'pekarnya', 'Cake', 29, true),
('Шаурмичная/кебаб-хаус', 'shaurmichnaya', 'Utensils', 30, true),
('Блинная/чебуречная', 'blinnaya', 'Utensils', 31, true),
('Вок-кафе/лапшичная', 'vok_kafe', 'Utensils', 32, true),
('Кальянная', 'kalyannnaya', 'Wind', 33, true),
('Частный детский сад', 'detskiy_sad', 'Baby', 34, true),
('Дом престарелых/пансионат', 'dom_prestarelyh', 'Heart', 35, true),
('Хоспис', 'hospis', 'Heart', 36, true),
('Реабилитационный центр', 'reabilitatsionnyy_tsentr', 'HeartPulse', 37, true),
('Психологический центр', 'psihologicheskiy_tsentr', 'Brain', 38, true),
('Стоматологическая клиника', 'stomatologiya', 'Smile', 39, true),
('Ветеринарная клиника', 'veterinarnaya', 'PawPrint', 40, true),
('Груминг-салон', 'gruming', 'Scissors', 41, true),
('Барбершоп', 'barbershop', 'Scissors', 42, true),
('Косметологический центр', 'kosmetologiya', 'Sparkles', 43, true),
('Массажный салон', 'massazhnyy_salon', 'Hand', 44, true),
('Студия маникюра/педикюра', 'manikyur', 'Paintbrush', 45, true),
('Студия депиляции', 'depilatsiya', 'Scissors', 46, true),
('Тату-студия', 'tatu_studiya', 'Pen', 47, true),
('Продуктовый магазин', 'produktovyy_magazin', 'ShoppingCart', 48, true),
('Магазин разливного пива', 'razlivnoe_pivo', 'Beer', 49, true),
('Алкомаркет/винотека', 'alkomarket', 'Wine', 50, true),
('Овощной/фруктовый магазин', 'ovoshchnoye', 'Apple', 51, true),
('Мясная лавка', 'myasnaya_lavka', 'Beef', 52, true),
('Зоомагазин', 'zoomagazin', 'PawPrint', 53, true),
('Магазин одежды/обуви', 'odezhda_obuv', 'ShoppingBag', 54, true),
('Магазин детских товаров', 'detskie_tovary', 'Baby', 55, true),
('Книжный/канцелярский магазин', 'knizhnyy', 'BookOpen', 56, true),
('Цветочный магазин', 'tsvetochnyy', 'Flower', 57, true),
('Хозтовары', 'hoztovary', 'Package', 58, true),
('Стройматериалы', 'stroymaterialy', 'HardHat', 59, true),
('Магазин автозапчастей', 'avtozapchasti', 'Car', 60, true),
('Табачный магазин/вейп-шоп', 'tabachnyy', 'Wind', 61, true),
('Химчистка-прачечная', 'himchistka', 'WashingMachine', 62, true),
('Ателье по ремонту одежды', 'atele', 'Scissors', 63, true),
('Мастерская по ремонту обуви', 'remont_obuvi', 'Wrench', 64, true),
('Часовая мастерская', 'chasovaya', 'Clock', 65, true),
('Фотосалон/фотостудия', 'fotosalon', 'Camera', 66, true),
('Копировальный центр/типография', 'tipografiya', 'Printer', 67, true),
('Танцевальная школа/йога-центр', 'tantsevalnaya_shkola', 'Music', 68, true),
('Детский игровой лабиринт', 'detskiy_labirint', 'Gamepad', 69, true),
('Тир', 'tir', 'Target', 70, true),
('Квест-комнаты', 'kvest_komnaty', 'Key', 71, true),
('Боулинг/бильярдный клуб', 'bouling', 'Circle', 72, true),
('Караоке-клуб', 'karaoke', 'Mic', 73, true),
('Хостел', 'hostel', 'BedDouble', 74, true),
('Мини-отель/гостевой дом', 'mini_otel', 'BedDouble', 75, true),
('Почасовой отель', 'pochassovoy_otel', 'Clock', 76, true),
('База отдыха/глэмпинг', 'baza_otdyha', 'Tent', 77, true),
('Пункт выдачи заказов (ПВЗ)', 'pvz', 'Package', 78, true)
ON CONFLICT (slug) DO NOTHING;