ALTER TABLE t_p71821556_real_estate_catalog_.seo_pages
  ADD COLUMN IF NOT EXISTS h2 TEXT,
  ADD COLUMN IF NOT EXISTS h3 TEXT,
  ADD COLUMN IF NOT EXISTS h4 TEXT,
  ADD COLUMN IF NOT EXISTS h5 TEXT,
  ADD COLUMN IF NOT EXISTS h6 TEXT,
  ADD COLUMN IF NOT EXISTS alt_text TEXT;