ALTER TABLE t_p71821556_real_estate_catalog_.settings
  ADD COLUMN IF NOT EXISTS vk_pixel_id TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS calltouch_id TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS telegram_ads_pixel TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ya_metrika_goals_enabled BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS max_autoreply_enabled BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS max_autoreply_text TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS max_user_id TEXT DEFAULT NULL;

ALTER TABLE t_p71821556_real_estate_catalog_.phone_contacts
  ADD COLUMN IF NOT EXISTS max_user_id TEXT DEFAULT NULL;
