ALTER TABLE t_p71821556_real_estate_catalog_.news_schedule
  ADD COLUMN IF NOT EXISTS price_digest_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS price_digest_day SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS price_digest_threshold DECIMAL(5,2) NOT NULL DEFAULT 3.0,
  ADD COLUMN IF NOT EXISTS price_digest_last_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS price_news_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS price_digest_max_enabled BOOLEAN NOT NULL DEFAULT FALSE;
