ALTER TABLE t_p71821556_real_estate_catalog_.market_listings
  ADD COLUMN IF NOT EXISTS lat NUMERIC(10,7) NULL,
  ADD COLUMN IF NOT EXISTS lng NUMERIC(10,7) NULL,
  ADD COLUMN IF NOT EXISTS building_year INTEGER NULL,
  ADD COLUMN IF NOT EXISTS wall_material VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS description TEXT NULL,
  ADD COLUMN IF NOT EXISTS street VARCHAR(200) NULL,
  ADD COLUMN IF NOT EXISTS ceiling_height NUMERIC(4,2) NULL,
  ADD COLUMN IF NOT EXISTS electricity_kw NUMERIC(8,2) NULL,
  ADD COLUMN IF NOT EXISTS has_security BOOLEAN NULL,
  ADD COLUMN IF NOT EXISTS has_ventilation BOOLEAN NULL,
  ADD COLUMN IF NOT EXISTS separate_entrance BOOLEAN NULL,
  ADD COLUMN IF NOT EXISTS photos_count INTEGER NULL;

CREATE INDEX IF NOT EXISTS idx_market_listings_lat_lng ON t_p71821556_real_estate_catalog_.market_listings(lat, lng);