CREATE TABLE t_p71821556_real_estate_catalog_.price_history_biweekly (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_recorded DATE NOT NULL,
  category VARCHAR(50) NOT NULL,
  deal_type VARCHAR(10) NOT NULL,
  price_per_m2 NUMERIC(12,2),
  change_pct NUMERIC(6,2),
  source VARCHAR(100) DEFAULT 'xlsx_import',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);