ALTER TABLE t_p71821556_real_estate_catalog_.listings
  ADD COLUMN IF NOT EXISTS is_assignment BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS rented_out BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS contract_end_date DATE DEFAULT NULL;